# Generated by Django 3.2.25 on 2024-06-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='type_file',
            field=models.CharField(choices=[('TEXT', 'text'), ('IMG', 'image'), ('VIDEO', 'video')], default=('TEXT', 'text'), max_length=10),
        ),
    ]
