# Generated by Django 3.2.25 on 2024-06-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_material_type_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='stage',
            field=models.IntegerField(default=1),
        ),
    ]
